<?php

$uri = get_template_directory_uri() . '/themethreads/assets/img/demos/';

// Demos
$demos = array(

	'original' => array(
		'title'       => esc_html__( 'Original', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'original.jpg',
		'preview'     => 'http://original.themethreadswp.com',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'agency' => array(
		'title'       => esc_html__( 'Agency', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'agency.jpg',
		'preview'     => 'http://agency.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'architecture' => array(
		'title'       => esc_html__( 'Architecture', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'architecture.jpg',
		'preview'     => 'http://architecture.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'beauty' => array(
		'title'       => esc_html__( 'Beauty', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'beauty.jpg',
		'preview'     => 'http://beauty.themethreadswp.com',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'blockchain' => array(
		'title'       => esc_html__( 'Blockchain', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'blockchain.jpg',
		'preview'     => 'http://blockchain.themethreadswp.com',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'blog-grid' => array(
		'title'       => esc_html__( 'Blog Grid', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'blog-grid.jpg',
		'preview'     => 'http://blog-grid.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'blogger' => array(
		'title'       => esc_html__( 'Blogger', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'blogger.jpg',
		'preview'     => 'http://blogger.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'blog-masonry' => array(
		'title'       => esc_html__( 'Blog Masonry', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'blog-masonry.jpg',
		'preview'     => 'http://blog-masonry.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'business' => array(
		'title'       => esc_html__( 'Business', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'business.jpg',
		'preview'     => 'http://business.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'services' => array(
		'title'       => esc_html__( 'Services', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'services.jpg',
		'preview'     => 'http://services.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'construction' => array(
		'title'       => esc_html__( 'Construction', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'construction.jpg',
		'preview'     => 'http://construction.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'creative' => array(
		'title'       => esc_html__( 'Creative', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'creative.jpg',
		'preview'     => 'http://creative.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'cryptocurrency' => array(
		'title'       => esc_html__( 'Crypto Currency', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'crypto-currency.jpg',
		'preview'     => 'http://cryptocurrency.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'digitalcreative' => array(
		'title'       => esc_html__( 'Digital Creative', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'digital-creative.jpg',
		'preview'     => 'http://digitalcreative.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'digitalagency' => array(
		'title'       => esc_html__( 'Digital Agency', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'digital-agency.jpg',
		'preview'     => 'http://digitalagency.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'freelancer' => array(
		'title'       => esc_html__( 'Freelancer', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'freelancer.jpg',
		'preview'     => 'http://freelancer.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'gym' => array(
		'title'       => esc_html__( 'Gym', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'gym.jpg',
		'preview'     => 'http://gym.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'landing' => array(
		'title'       => esc_html__( 'Landing', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'landing.jpg',
		'preview'     => 'http://landing.themethreadswp.com',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'hotel' => array(
		'title'       => esc_html__( 'Hotel', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'hotel.jpg',
		'preview'     => 'http://hotel.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'multi-concept' => array(
		'title'       => esc_html__( 'Multiconcept', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'multi-concept.jpg',
		'preview'     => 'http://multiconcept.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'magazine' => array(
		'title'       => esc_html__( 'Magazine', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'magazine.jpg',
		'preview'     => 'http://magazine.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'medical' => array(
		'title'       => esc_html__( 'Medical', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'medical.jpg',
		'preview'     => 'http://medical.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'opus-1' => array(
		'title'       => esc_html__( 'Opus', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'opus-1.jpg',
		'preview'     => 'http://opus.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'opus-2' => array(
		'title'       => esc_html__( 'Opus 2', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'opus-2.jpg',
		'preview'     => 'http://opus-two.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'opus-3' => array(
		'title'       => esc_html__( 'Opus 3', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'opus-3.jpg',
		'preview'     => 'http://opus-three.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'opus-4' => array(
		'title'       => esc_html__( 'Opus 4', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'opus-4.jpg',
		'preview'     => 'http://opus-four.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'personal' => array(
		'title'       => esc_html__( 'Personal', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'personal.jpg',
		'preview'     => 'http://personal.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'minimal-magazine' => array(
		'title'       => esc_html__( 'Minimal Magazine', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'minimal-magazine.jpg',
		'preview'     => 'http://minimal-magazine.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portfolio-dynamic' => array(
		'title'       => esc_html__( 'Portfolio Dynamic', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio-dynamic.jpg',
		'preview'     => 'http://portfolio-dynamic.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'avantgarde' => array(
		'title'       => esc_html__( 'Avantgarde', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'avantgarde.jpg',
		'preview'     => 'http://avantgarde.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portfolio-grid' => array(
		'title'       => esc_html__( 'Portfolio Grid', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio-grid.jpg',
		'preview'     => 'http://portfolio-grid.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portfolio-masonry' => array(
		'title'       => esc_html__( 'Portfolio Masonry', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio-masonry.jpg',
		'preview'     => 'http://portfolio-masonry.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portfolio-modern' => array(
		'title'       => esc_html__( 'Portfolio Modern', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio-modern.jpg',
		'preview'     => 'http://portfolio-modern.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portfolio' => array(
		'title'       => esc_html__( 'Portfolio', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio.jpg',
		'preview'     => 'http://portfolio.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'rtl' => array(
		'title'       => esc_html__( 'RTL', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'rtl.jpg',
		'preview'     => 'http://rtl.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'mobile' => array(
		'title'       => esc_html__( 'Mobile', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'mobile.jpg',
		'preview'     => 'http://mobile.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'shop' => array(
		'title'       => esc_html__( 'Shop', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'shop.jpg',
		'preview'     => 'http://shop.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'stack' => array(
		'title'       => esc_html__( 'Stack', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'stack.jpg',
		'preview'     => 'http://stack.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'travel' => array(
		'title'       => esc_html__( 'Travel', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'travel.jpg',
		'preview'     => 'http://travel.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portrait' => array(
		'title'       => esc_html__( 'Portrait', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'portrait.jpg',
		'preview'     => 'http://portrait.themethreadswp.com',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'photographer' => array(
		'title'       => esc_html__( 'Photographer', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'photographer.jpg',
		'preview'     => 'http://photographer.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'voguish' => array(
		'title'       => esc_html__( 'Voguish', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'voguish.jpg',
		'preview'     => 'http://voguish.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'wave' => array(
		'title'       => esc_html__( 'Wave', 'volley' ),	
		'description' => '',
		'screenshot'  => $uri . 'wave.jpg',
		'preview'     => 'http://wave.themethreadswp.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),

);